### ISSUE TITLE
Can't run with it

### ISSUE THREAD

**Issue by shuaizhiwen** [cksac/dataloader-rs#1]
![image](https://user-images.githubusercontent.com/28283255/34026034-57562aba-e18e-11e7-89a5-63e845ca5a55.png)
![image](https://user-images.githubusercontent.com/28283255/34026045-61272fee-e18e-11e7-8c87-1c9c0a75fc75.png)
I'm sorry to bother you, but I have a problem. I hope I can get your help.thank you very much!

**Comment by cksac** [comment]
Seems since futures 0.1.15 has the problem, I have push a new version (0.5.1) to fix that.
