### ISSUE TITLE
Why dataloader is handling errors?

### ISSUE THREAD

**Issue by IcanDivideBy0** [cksac/dataloader-rs#17]
Hello,
I'm wondering why cached loader have to handle errors, I don't see any particular treatment done on the results in this crate. Wouldn't it be simpler if loader can handle whatever value users want it to handle.

Loader could be declared as follows:
```rust
pub struct Loader<K, V, F, C = HashMap<K, V>>
where
    K: Eq + Hash + Clone,
    V: Clone,
    F: BatchFn<K, V>,
    C: Cache<Key = K, Val = V>,
```
This  would still allow for anyone to put a (cloneable) `Result` as output value.

In particular I'd like to use the loader to return a `Vec<Result<_, _>>` for each key given to the `BatchFn`; What do you think about this design change ?

**Comment by cksac** [comment]
> In particular I'd like to use the loader to return a Vec<Result<_, _>> for each key given to the BatchFn

 Could you elaborate more?

**Comment by IcanDivideBy0** [comment]
I'm currently having something like this
```
struct User { id: ID }
struct Order { id: ID, user: ID }

impl User {
    async fn orders(self, ctx: &Context<'_>) -> Vec<Result<Order>> {
       let user_orders_loader; // get the loader from context
       user_orders_loader.load(self.id).await
    }
}
```

My batch fn behind the loader have the following signature:

```
async fn load(&self, keys: &[ID]) -> HashMap<ID, Result<Vec<T>>>
```

The thing is that during the batch load, each document can fail individually, not necessary as a batch.

**Comment by cksac** [comment]
please try new version `dataloader = "0.12.0"`.  removed associated type `Error` in `BatchFn`
```rust
#[async_trait]
pub trait BatchFn<K, V> {
    async fn load(&self, keys: &[K]) -> HashMap<K, V>
    where
        K: 'async_trait,
        V: 'async_trait;
}
```

**Comment by IcanDivideBy0** [comment]
You're faster than light!
All good to me :)
