### ISSUE TITLE
Consider adding prime_many to loader interface

### ISSUE THREAD

**Issue by gzp-crey** [cksac/dataloader-rs#27]
Ex when a search result returns not just the keys but the data itself, it'd be good to populate the cache from the response. Thus any new request to the already know values can be omitted.
As I see prime can be used to add values to the cache, but it performs a lock on each addition. prime_many could accept an iterator of (K,V) pairs and could hold the lock for the entire update.

Or is there any other option to fill/add to the loader a known value ?

**Comment by cksac** [comment]
Hi, if use cached::Loader, it will save result into cache already.

**Comment by cksac** [comment]
add prime_many to cached::Loader, think it still useful for preload some responses to the loader.

**Comment by gzp-crey** [comment]
> 
> 
> Hi, if use cached::Loader, it will save result into cache already.

As I see caching happens when load triggers the BatchFn implementation, that operates on keys only.
In may case the data is collected outside of a key based load:

some more details:
the "load", easy path:
- type of key = i32
- invoke load_many([1,2,3])
- it calls the BatchFn  implementation (with a slice of i32)
- all is fine
but if I have a set of key/value pair from a non-loader triggered query (ex a response for a search result, where the response contains the full values not just the keys (1,2,3 in the above example)) I see no way to populate the cache in one step.

(I'm using dataloader for graphql evaluation with juniper, and as I see the best if I cache everything while the whole response is "ready")

**Comment by cksac** [comment]
I see, thanks for detail explanation. Will publish new version with prime_many soon
