### ISSUE TITLE
Upgrading to std Futures and latest tokio

### ISSUE THREAD

**Issue by tyranron** [cksac/dataloader-rs#3]
Hi, there! Thank you for this crate 🙇

I'd like to use it extensively, but is it still maintained? The latest change was made at Aug 4 2018 and `master` depends on `tokio-core`, which is deprecated long ago.

How about upgrading to the latest `tokio` and refactoring with `std` `Future`s which will come in the nearest 1.36 Rust release? Would you mind on my elaboration on it?

**Comment by cksac** [comment]
Hi, I do plan to migrate to `std Future` later

**Comment by tyranron** [comment]
@cksac would you mind if I start the work in a fork+PR and you will review/improve/merge it later when you're ready to migrate to `std Future`?

**Comment by cksac** [comment]
@tyranron that will be great :)
