### ISSUE TITLE
Specify fields in key, or allow separate load/cache keys

### ISSUE THREAD

**Issue by oeed** [cksac/dataloader-rs#31]
I am wanting to only load requested fields from the database. For example, take this GraphQL type:

```gql
type Person {
  id
  name
  birthday
}
```

With the following request:
```gql
person {
  id
  name
}
```

Rather than doing `SELECT * FROM people`, I want to only get the `id` and `name` fields; not `birthday`.

It seems that in the official Node based module they [recommend](https://github.com/graphql/dataloader/issues/236#issuecomment-598228953) using separate cache and load keys. This means `BatchFn` might use `(PersonID, Vec<String>)` as its ID, but `Loader` would use `PersonID`. Multiple load keys map to one cache key; so it'd be up to the `BatchFn` implementation to dedup the person/fields combinations.

**Comment by cksac** [comment]
I have few questions unresolved, 
1. In case the graphql query contains multiple segments each require different set of fields, e.g. (PersonId(1), vec!["id"]), (PersonId(1), vec!["id", "name"]) both will return rust struct `Person` which container all the fields, how batchFn to be implemented?
```rust
pub struct Person {
   id: String,
   name: String,
   birthday: String
}

impl BatchFn<(PersonID, Vec<String>), Person> for PersonBatcher {
...
}
```
2. If (PersonId(1), vec!["id"]), (PersonId(1), vec!["id", "name"]) will resolved to same cache, then it will fire two queries to DB?
e.g. select id from person,  select id, name from person
there has multiple queries for same PersonId, and merged result into single cache, in case there have update in between the queries, the cache may have inconsistency
