### ISSUE TITLE
Feature Request: Arbitrary request batching future

### ISSUE THREAD

**Issue by Xaeroxe** [cksac/dataloader-rs#38]
My team doesn't particularly like the impact that [this](https://github.com/cksac/dataloader-rs/blob/5c5dd8e70558bd1818fbe01aaccc4fd89a791505/src/non_cached.rs#L125) has on our CPU flamegraph. We're also not entirely content with the idea of just adjusting the yield count, we want more complex behavior at this spot. In my own fork I'm going to make it so that the API allows an arbitrary future to replace this yielding behavior. Would you be interested in a PR of this to contribute that feature back upstream?

**Comment by cksac** [comment]
yes, I think others might want that feature too.
