### ISSUE TITLE
Which version should I use?

### ISSUE THREAD

**Issue by acelot** [cksac/dataloader-rs#8]
`0.5.1` from crates or `0.6.0-dev`? When will the new release be in the crates.io?

**Comment by acelot** [comment]
https://blog.rust-lang.org/2019/11/07/Rust-1.39.0.html 🎉🎉🎉

**Comment by cksac** [comment]
Still need to wait the ecosystem upgrade to futures 0.3, i.e one of the dependency [futures-timer](https://github.com/async-rs/futures-timer)

**Comment by cksac** [comment]
version 0.6 published
